name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-binaries
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install plotting deps
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib
      - name: Build plots and PDFs
        run: |
          make plots || true
          make paper
          make paper-unordered || true
          make paper-main || true
          make dist || true
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md
          files: |
            tex/true_string_collision.pdf
            tex/true_string_unordered.pdf
            tex/main.pdf
            dist/release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}